title: "Program Evaluation and Administrative Statistical Analysis"
description: "PA 5312 textbook — Texas State University"
author: "Dr. W. Scott Langford"
url: "https://pa5312.scottlangford.com"
baseurl: ""
theme: minima
plugins:
  - jekyll-seo-tag

header_pages:
  - docs/chapter1.md
  - docs/chapter2.md
  - docs/chapter3.md
  - docs/chapter4.md
  - docs/chapter5.md
  - docs/chapter6.md
  - docs/chapter7.md
  - docs/chapter8.md
  - docs/chapter9.md
  - docs/chapter10.md
  - docs/chapter11.md
  - docs/chapter12.md
  - docs/datasets.md
